packages:
  - "apps/*"
  - "examples/*"
  - "packages/*"
  - "packages/api/*"
  - "packages/api/client/*"
  - "packages/events/*"
  - "packages/helpers/*"
  - "packages/oauth/*"
  - "packages/telemetry/*"
  - "packages/telemetry/client/*"
  - "services/*"
