packages:
  - "examples/*"
  - "packages/api/*"
  - "packages/api/client/*"
  - "packages/helpers/*"
  - "packages/oauth/*"
allowBuilds:
  "@nestjs/core": false
  "@openapitools/openapi-generator-cli": false
  esbuild: true
