/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  IracingAPIResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IracingAPIResponseFromJSON,
    IracingAPIResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class CarclassApi extends runtime.BaseAPI {

    /**
     * Gets car classes.
     */
    async getCarClassRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/carclass/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     * Gets car classes.
     */
    async getCarClass(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getCarClassRaw(initOverrides);
        return await response.value();
    }

}
