/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  IracingAPIResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IracingAPIResponseFromJSON,
    IracingAPIResponseToJSON,
} from '../models/index';

export interface GetLeagueRequest {
    league_id: number;
    include_licenses?: boolean;
}

export interface GetLeagueCustomerLeagueSessionsRequest {
    mine?: boolean;
    package_id?: number;
}

export interface GetLeagueDirectoryRequest {
    search?: string;
    tag?: string;
    restrict_to_member?: boolean;
    restrict_to_recruiting?: boolean;
    restrict_to_friends?: boolean;
    restrict_to_watched?: boolean;
    minimum_roster_count?: number;
    maximum_roster_count?: number;
    lowerbound?: number;
    upperbound?: number;
    sort?: string;
    order?: string;
}

export interface GetLeagueMembershipRequest {
    cust_id?: number;
    include_league?: boolean;
}

export interface GetLeaguePointsSystemsRequest {
    league_id: number;
    season_id?: number;
}

export interface GetLeagueRosterRequest {
    league_id: number;
    include_licenses?: boolean;
}

export interface GetLeagueSeasonSessionsRequest {
    league_id: number;
    season_id: number;
    results_only?: boolean;
}

export interface GetLeagueSeasonStandingsRequest {
    league_id: number;
    season_id: number;
    car_class_id?: number;
    car_id?: number;
}

export interface GetLeagueSeasonsRequest {
    league_id: number;
    retired?: boolean;
}

/**
 * 
 */
export class LeagueApi extends runtime.BaseAPI {

    /**
     */
    async getLeagueRaw(requestParameters: GetLeagueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['league_id'] == null) {
            throw new runtime.RequiredError(
                'league_id',
                'Required parameter "league_id" was null or undefined when calling getLeague().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['league_id'] != null) {
            queryParameters['league_id'] = requestParameters['league_id'];
        }

        if (requestParameters['include_licenses'] != null) {
            queryParameters['include_licenses'] = requestParameters['include_licenses'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/league/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeague(requestParameters: GetLeagueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getLeagueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLeagueCustomerLeagueSessionsRaw(requestParameters: GetLeagueCustomerLeagueSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['mine'] != null) {
            queryParameters['mine'] = requestParameters['mine'];
        }

        if (requestParameters['package_id'] != null) {
            queryParameters['package_id'] = requestParameters['package_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/league/cust_league_sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeagueCustomerLeagueSessions(requestParameters: GetLeagueCustomerLeagueSessionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getLeagueCustomerLeagueSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLeagueDirectoryRaw(requestParameters: GetLeagueDirectoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['restrict_to_member'] != null) {
            queryParameters['restrict_to_member'] = requestParameters['restrict_to_member'];
        }

        if (requestParameters['restrict_to_recruiting'] != null) {
            queryParameters['restrict_to_recruiting'] = requestParameters['restrict_to_recruiting'];
        }

        if (requestParameters['restrict_to_friends'] != null) {
            queryParameters['restrict_to_friends'] = requestParameters['restrict_to_friends'];
        }

        if (requestParameters['restrict_to_watched'] != null) {
            queryParameters['restrict_to_watched'] = requestParameters['restrict_to_watched'];
        }

        if (requestParameters['minimum_roster_count'] != null) {
            queryParameters['minimum_roster_count'] = requestParameters['minimum_roster_count'];
        }

        if (requestParameters['maximum_roster_count'] != null) {
            queryParameters['maximum_roster_count'] = requestParameters['maximum_roster_count'];
        }

        if (requestParameters['lowerbound'] != null) {
            queryParameters['lowerbound'] = requestParameters['lowerbound'];
        }

        if (requestParameters['upperbound'] != null) {
            queryParameters['upperbound'] = requestParameters['upperbound'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/league/directory`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeagueDirectory(requestParameters: GetLeagueDirectoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getLeagueDirectoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLeagueMembershipRaw(requestParameters: GetLeagueMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        if (requestParameters['include_league'] != null) {
            queryParameters['include_league'] = requestParameters['include_league'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/league/membership`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeagueMembership(requestParameters: GetLeagueMembershipRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getLeagueMembershipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLeaguePointsSystemsRaw(requestParameters: GetLeaguePointsSystemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['league_id'] == null) {
            throw new runtime.RequiredError(
                'league_id',
                'Required parameter "league_id" was null or undefined when calling getLeaguePointsSystems().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['league_id'] != null) {
            queryParameters['league_id'] = requestParameters['league_id'];
        }

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/league/get_points_systems`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeaguePointsSystems(requestParameters: GetLeaguePointsSystemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getLeaguePointsSystemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLeagueRosterRaw(requestParameters: GetLeagueRosterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['league_id'] == null) {
            throw new runtime.RequiredError(
                'league_id',
                'Required parameter "league_id" was null or undefined when calling getLeagueRoster().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['league_id'] != null) {
            queryParameters['league_id'] = requestParameters['league_id'];
        }

        if (requestParameters['include_licenses'] != null) {
            queryParameters['include_licenses'] = requestParameters['include_licenses'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/league/roster`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeagueRoster(requestParameters: GetLeagueRosterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getLeagueRosterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLeagueSeasonSessionsRaw(requestParameters: GetLeagueSeasonSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['league_id'] == null) {
            throw new runtime.RequiredError(
                'league_id',
                'Required parameter "league_id" was null or undefined when calling getLeagueSeasonSessions().'
            );
        }

        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getLeagueSeasonSessions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['league_id'] != null) {
            queryParameters['league_id'] = requestParameters['league_id'];
        }

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['results_only'] != null) {
            queryParameters['results_only'] = requestParameters['results_only'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/league/season_sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeagueSeasonSessions(requestParameters: GetLeagueSeasonSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getLeagueSeasonSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLeagueSeasonStandingsRaw(requestParameters: GetLeagueSeasonStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['league_id'] == null) {
            throw new runtime.RequiredError(
                'league_id',
                'Required parameter "league_id" was null or undefined when calling getLeagueSeasonStandings().'
            );
        }

        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getLeagueSeasonStandings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['league_id'] != null) {
            queryParameters['league_id'] = requestParameters['league_id'];
        }

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['car_class_id'] != null) {
            queryParameters['car_class_id'] = requestParameters['car_class_id'];
        }

        if (requestParameters['car_id'] != null) {
            queryParameters['car_id'] = requestParameters['car_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/league/season_standings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeagueSeasonStandings(requestParameters: GetLeagueSeasonStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getLeagueSeasonStandingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLeagueSeasonsRaw(requestParameters: GetLeagueSeasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['league_id'] == null) {
            throw new runtime.RequiredError(
                'league_id',
                'Required parameter "league_id" was null or undefined when calling getLeagueSeasons().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['league_id'] != null) {
            queryParameters['league_id'] = requestParameters['league_id'];
        }

        if (requestParameters['retired'] != null) {
            queryParameters['retired'] = requestParameters['retired'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/league/seasons`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeagueSeasons(requestParameters: GetLeagueSeasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getLeagueSeasonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
