/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  IracingAPIResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IracingAPIResponseFromJSON,
    IracingAPIResponseToJSON,
} from '../models/index';

export interface GetMemberRequest {
    cust_ids: string;
    include_licenses?: boolean;
}

export interface GetMemberAwardInstancesRequest {
    award_id: number;
    cust_id?: number;
}

export interface GetMemberAwardsRequest {
    cust_id?: number;
}

export interface GetMemberChartDataRequest {
    category_id: number;
    chart_type: number;
    cust_id?: number;
}

export interface GetMemberProfileRequest {
    cust_id?: number;
}

/**
 * 
 */
export class MemberApi extends runtime.BaseAPI {

    /**
     */
    async getMemberRaw(requestParameters: GetMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['cust_ids'] == null) {
            throw new runtime.RequiredError(
                'cust_ids',
                'Required parameter "cust_ids" was null or undefined when calling getMember().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cust_ids'] != null) {
            queryParameters['cust_ids'] = requestParameters['cust_ids'];
        }

        if (requestParameters['include_licenses'] != null) {
            queryParameters['include_licenses'] = requestParameters['include_licenses'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/member/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMember(requestParameters: GetMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMemberAwardInstancesRaw(requestParameters: GetMemberAwardInstancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['award_id'] == null) {
            throw new runtime.RequiredError(
                'award_id',
                'Required parameter "award_id" was null or undefined when calling getMemberAwardInstances().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        if (requestParameters['award_id'] != null) {
            queryParameters['award_id'] = requestParameters['award_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/member/award_instances`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMemberAwardInstances(requestParameters: GetMemberAwardInstancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getMemberAwardInstancesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMemberAwardsRaw(requestParameters: GetMemberAwardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/member/awards`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMemberAwards(requestParameters: GetMemberAwardsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getMemberAwardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMemberChartDataRaw(requestParameters: GetMemberChartDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['category_id'] == null) {
            throw new runtime.RequiredError(
                'category_id',
                'Required parameter "category_id" was null or undefined when calling getMemberChartData().'
            );
        }

        if (requestParameters['chart_type'] == null) {
            throw new runtime.RequiredError(
                'chart_type',
                'Required parameter "chart_type" was null or undefined when calling getMemberChartData().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        if (requestParameters['category_id'] != null) {
            queryParameters['category_id'] = requestParameters['category_id'];
        }

        if (requestParameters['chart_type'] != null) {
            queryParameters['chart_type'] = requestParameters['chart_type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/member/chart_data`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMemberChartData(requestParameters: GetMemberChartDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getMemberChartDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMemberInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/member/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMemberInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getMemberInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getMemberParticipationCreditsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/member/participation_credits`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMemberParticipationCredits(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getMemberParticipationCreditsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Gets a requested user\'s profile.
     */
    async getMemberProfileRaw(requestParameters: GetMemberProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/member/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     * Gets a requested user\'s profile.
     */
    async getMemberProfile(requestParameters: GetMemberProfileRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getMemberProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
