/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  IracingAPIResponse,
  IracingEventType,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IracingAPIResponseFromJSON,
    IracingAPIResponseToJSON,
    IracingEventTypeFromJSON,
    IracingEventTypeToJSON,
} from '../models/index';

export interface GetResultsRequest {
    subsession_id: number;
    include_licenses?: boolean;
}

export interface GetResultsEventLogRequest {
    subsession_id: number;
    simsession_number: number;
}

export interface GetResultsLapChartDataRequest {
    subsession_id: number;
    simsession_number: number;
}

export interface GetResultsLapDataRequest {
    subsession_id: number;
    simsession_number: number;
    cust_id?: number;
    team_id?: number;
}

export interface GetResultsSearchHostedRequest {
    start_range_begin?: Date;
    start_range_end?: Date;
    finish_range_begin?: Date;
    finish_range_end?: Date;
    cust_id?: number;
    team_id?: number;
    host_cust_id?: number;
    session_name?: string;
    league_id?: number;
    league_season_id?: number;
    car_id?: number;
    track_id?: number;
    category_ids?: string;
}

export interface GetResultsSearchSeriesRequest {
    season_year?: number;
    season_quarter?: number;
    start_range_begin?: Date;
    start_range_end?: Date;
    finish_range_begin?: Date;
    finish_range_end?: Date;
    cust_id?: number;
    team_id?: number;
    series_id?: number;
    race_week_num?: number;
    official_only?: boolean;
    event_types?: string;
    category_ids?: string;
}

export interface GetResultsSeasonResultsRequest {
    season_id: number;
    event_type?: IracingEventType;
    race_week_num?: number;
}

/**
 * 
 */
export class ResultsApi extends runtime.BaseAPI {

    /**
     */
    async getResultsRaw(requestParameters: GetResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['subsession_id'] == null) {
            throw new runtime.RequiredError(
                'subsession_id',
                'Required parameter "subsession_id" was null or undefined when calling getResults().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['subsession_id'] != null) {
            queryParameters['subsession_id'] = requestParameters['subsession_id'];
        }

        if (requestParameters['include_licenses'] != null) {
            queryParameters['include_licenses'] = requestParameters['include_licenses'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/results/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getResults(requestParameters: GetResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getResultsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getResultsEventLogRaw(requestParameters: GetResultsEventLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['subsession_id'] == null) {
            throw new runtime.RequiredError(
                'subsession_id',
                'Required parameter "subsession_id" was null or undefined when calling getResultsEventLog().'
            );
        }

        if (requestParameters['simsession_number'] == null) {
            throw new runtime.RequiredError(
                'simsession_number',
                'Required parameter "simsession_number" was null or undefined when calling getResultsEventLog().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['subsession_id'] != null) {
            queryParameters['subsession_id'] = requestParameters['subsession_id'];
        }

        if (requestParameters['simsession_number'] != null) {
            queryParameters['simsession_number'] = requestParameters['simsession_number'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/results/event_log`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getResultsEventLog(requestParameters: GetResultsEventLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getResultsEventLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getResultsLapChartDataRaw(requestParameters: GetResultsLapChartDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['subsession_id'] == null) {
            throw new runtime.RequiredError(
                'subsession_id',
                'Required parameter "subsession_id" was null or undefined when calling getResultsLapChartData().'
            );
        }

        if (requestParameters['simsession_number'] == null) {
            throw new runtime.RequiredError(
                'simsession_number',
                'Required parameter "simsession_number" was null or undefined when calling getResultsLapChartData().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['subsession_id'] != null) {
            queryParameters['subsession_id'] = requestParameters['subsession_id'];
        }

        if (requestParameters['simsession_number'] != null) {
            queryParameters['simsession_number'] = requestParameters['simsession_number'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/results/lap_chart_data`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getResultsLapChartData(requestParameters: GetResultsLapChartDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getResultsLapChartDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getResultsLapDataRaw(requestParameters: GetResultsLapDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['subsession_id'] == null) {
            throw new runtime.RequiredError(
                'subsession_id',
                'Required parameter "subsession_id" was null or undefined when calling getResultsLapData().'
            );
        }

        if (requestParameters['simsession_number'] == null) {
            throw new runtime.RequiredError(
                'simsession_number',
                'Required parameter "simsession_number" was null or undefined when calling getResultsLapData().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['subsession_id'] != null) {
            queryParameters['subsession_id'] = requestParameters['subsession_id'];
        }

        if (requestParameters['simsession_number'] != null) {
            queryParameters['simsession_number'] = requestParameters['simsession_number'];
        }

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        if (requestParameters['team_id'] != null) {
            queryParameters['team_id'] = requestParameters['team_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/results/lap_data`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getResultsLapData(requestParameters: GetResultsLapDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getResultsLapDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getResultsSearchHostedRaw(requestParameters: GetResultsSearchHostedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['start_range_begin'] != null) {
            queryParameters['start_range_begin'] = requestParameters['start_range_begin'];
        }

        if (requestParameters['start_range_end'] != null) {
            queryParameters['start_range_end'] = requestParameters['start_range_end'];
        }

        if (requestParameters['finish_range_begin'] != null) {
            queryParameters['finish_range_begin'] = requestParameters['finish_range_begin'];
        }

        if (requestParameters['finish_range_end'] != null) {
            queryParameters['finish_range_end'] = requestParameters['finish_range_end'];
        }

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        if (requestParameters['team_id'] != null) {
            queryParameters['team_id'] = requestParameters['team_id'];
        }

        if (requestParameters['host_cust_id'] != null) {
            queryParameters['host_cust_id'] = requestParameters['host_cust_id'];
        }

        if (requestParameters['session_name'] != null) {
            queryParameters['session_name'] = requestParameters['session_name'];
        }

        if (requestParameters['league_id'] != null) {
            queryParameters['league_id'] = requestParameters['league_id'];
        }

        if (requestParameters['league_season_id'] != null) {
            queryParameters['league_season_id'] = requestParameters['league_season_id'];
        }

        if (requestParameters['car_id'] != null) {
            queryParameters['car_id'] = requestParameters['car_id'];
        }

        if (requestParameters['track_id'] != null) {
            queryParameters['track_id'] = requestParameters['track_id'];
        }

        if (requestParameters['category_ids'] != null) {
            queryParameters['category_ids'] = requestParameters['category_ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/results/search_hosted`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getResultsSearchHosted(requestParameters: GetResultsSearchHostedRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getResultsSearchHostedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getResultsSearchSeriesRaw(requestParameters: GetResultsSearchSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['season_year'] != null) {
            queryParameters['season_year'] = requestParameters['season_year'];
        }

        if (requestParameters['season_quarter'] != null) {
            queryParameters['season_quarter'] = requestParameters['season_quarter'];
        }

        if (requestParameters['start_range_begin'] != null) {
            queryParameters['start_range_begin'] = requestParameters['start_range_begin'];
        }

        if (requestParameters['start_range_end'] != null) {
            queryParameters['start_range_end'] = requestParameters['start_range_end'];
        }

        if (requestParameters['finish_range_begin'] != null) {
            queryParameters['finish_range_begin'] = requestParameters['finish_range_begin'];
        }

        if (requestParameters['finish_range_end'] != null) {
            queryParameters['finish_range_end'] = requestParameters['finish_range_end'];
        }

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        if (requestParameters['team_id'] != null) {
            queryParameters['team_id'] = requestParameters['team_id'];
        }

        if (requestParameters['series_id'] != null) {
            queryParameters['series_id'] = requestParameters['series_id'];
        }

        if (requestParameters['race_week_num'] != null) {
            queryParameters['race_week_num'] = requestParameters['race_week_num'];
        }

        if (requestParameters['official_only'] != null) {
            queryParameters['official_only'] = requestParameters['official_only'];
        }

        if (requestParameters['event_types'] != null) {
            queryParameters['event_types'] = requestParameters['event_types'];
        }

        if (requestParameters['category_ids'] != null) {
            queryParameters['category_ids'] = requestParameters['category_ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/results/search_series`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getResultsSearchSeries(requestParameters: GetResultsSearchSeriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getResultsSearchSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getResultsSeasonResultsRaw(requestParameters: GetResultsSeasonResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getResultsSeasonResults().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['event_type'] != null) {
            queryParameters['event_type'] = requestParameters['event_type'];
        }

        if (requestParameters['race_week_num'] != null) {
            queryParameters['race_week_num'] = requestParameters['race_week_num'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/results/season_results`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getResultsSeasonResults(requestParameters: GetResultsSeasonResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getResultsSeasonResultsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
