/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  IracingAPIResponse,
  IracingEventType,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IracingAPIResponseFromJSON,
    IracingAPIResponseToJSON,
    IracingEventTypeFromJSON,
    IracingEventTypeToJSON,
} from '../models/index';

export interface GetSeasonListRequest {
    season_year: number;
    season_quarter: number;
}

export interface GetSeasonRaceGuideRequest {
    from?: Date;
    include_end_after_from?: boolean;
}

export interface GetSeasonSpectatorSubsessionIdsRequest {
    event_types?: Array<IracingEventType>;
}

export interface GetSeasonSpectatorSubsessionIdsDetailRequest {
    event_types?: Array<IracingEventType>;
    season_ids?: Array<number>;
}

/**
 * 
 */
export class SeasonApi extends runtime.BaseAPI {

    /**
     */
    async getSeasonListRaw(requestParameters: GetSeasonListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_year'] == null) {
            throw new runtime.RequiredError(
                'season_year',
                'Required parameter "season_year" was null or undefined when calling getSeasonList().'
            );
        }

        if (requestParameters['season_quarter'] == null) {
            throw new runtime.RequiredError(
                'season_quarter',
                'Required parameter "season_quarter" was null or undefined when calling getSeasonList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_year'] != null) {
            queryParameters['season_year'] = requestParameters['season_year'];
        }

        if (requestParameters['season_quarter'] != null) {
            queryParameters['season_quarter'] = requestParameters['season_quarter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/season/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeasonList(requestParameters: GetSeasonListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeasonListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeasonRaceGuideRaw(requestParameters: GetSeasonRaceGuideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['include_end_after_from'] != null) {
            queryParameters['include_end_after_from'] = requestParameters['include_end_after_from'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/season/race_guide`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeasonRaceGuide(requestParameters: GetSeasonRaceGuideRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeasonRaceGuideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeasonSpectatorSubsessionIdsRaw(requestParameters: GetSeasonSpectatorSubsessionIdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['event_types'] != null) {
            queryParameters['event_types'] = requestParameters['event_types'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/season/spectator_subsessionids`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeasonSpectatorSubsessionIds(requestParameters: GetSeasonSpectatorSubsessionIdsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeasonSpectatorSubsessionIdsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeasonSpectatorSubsessionIdsDetailRaw(requestParameters: GetSeasonSpectatorSubsessionIdsDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['event_types'] != null) {
            queryParameters['event_types'] = requestParameters['event_types'];
        }

        if (requestParameters['season_ids'] != null) {
            queryParameters['season_ids'] = requestParameters['season_ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/season/spectator_subsessionids_detail`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeasonSpectatorSubsessionIdsDetail(requestParameters: GetSeasonSpectatorSubsessionIdsDetailRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeasonSpectatorSubsessionIdsDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
