/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  IracingAPIResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IracingAPIResponseFromJSON,
    IracingAPIResponseToJSON,
} from '../models/index';

export interface GetSeriesPastSeasonsRequest {
    series_id: number;
}

export interface GetSeriesSeasonListRequest {
    include_series?: boolean;
    season_year?: number;
    season_quarter?: number;
}

export interface GetSeriesSeasonScheduleRequest {
    season_id: number;
}

export interface GetSeriesSeasonsRequest {
    include_series?: boolean;
    season_year?: number;
    season_quarter?: number;
}

/**
 * 
 */
export class SeriesApi extends runtime.BaseAPI {

    /**
     */
    async getSeriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/series/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeries(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeriesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeriesAssetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/series/assets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeriesAssets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeriesAssetsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeriesPastSeasonsRaw(requestParameters: GetSeriesPastSeasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['series_id'] == null) {
            throw new runtime.RequiredError(
                'series_id',
                'Required parameter "series_id" was null or undefined when calling getSeriesPastSeasons().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['series_id'] != null) {
            queryParameters['series_id'] = requestParameters['series_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/series/past_seasons`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeriesPastSeasons(requestParameters: GetSeriesPastSeasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeriesPastSeasonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeriesSeasonListRaw(requestParameters: GetSeriesSeasonListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['include_series'] != null) {
            queryParameters['include_series'] = requestParameters['include_series'];
        }

        if (requestParameters['season_year'] != null) {
            queryParameters['season_year'] = requestParameters['season_year'];
        }

        if (requestParameters['season_quarter'] != null) {
            queryParameters['season_quarter'] = requestParameters['season_quarter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/series/season_list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeriesSeasonList(requestParameters: GetSeriesSeasonListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeriesSeasonListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeriesSeasonScheduleRaw(requestParameters: GetSeriesSeasonScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getSeriesSeasonSchedule().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/series/season_schedule`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeriesSeasonSchedule(requestParameters: GetSeriesSeasonScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeriesSeasonScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeriesSeasonsRaw(requestParameters: GetSeriesSeasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['include_series'] != null) {
            queryParameters['include_series'] = requestParameters['include_series'];
        }

        if (requestParameters['season_year'] != null) {
            queryParameters['season_year'] = requestParameters['season_year'];
        }

        if (requestParameters['season_quarter'] != null) {
            queryParameters['season_quarter'] = requestParameters['season_quarter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/series/seasons`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeriesSeasons(requestParameters: GetSeriesSeasonsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeriesSeasonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeriesStatsSeriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/series/stats_series`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSeriesStatsSeries(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getSeriesStatsSeriesRaw(initOverrides);
        return await response.value();
    }

}
