/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  IracingAPIResponse,
  IracingDivision,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IracingAPIResponseFromJSON,
    IracingAPIResponseToJSON,
    IracingDivisionFromJSON,
    IracingDivisionToJSON,
} from '../models/index';

export interface GetStatsMemberBestsRequest {
    cust_id?: number;
    car_id?: number;
}

export interface GetStatsMemberCareerRequest {
    cust_id?: number;
}

export interface GetStatsMemberDivisionRequest {
    season_id: number;
    event_type: GetStatsMemberDivisionEventTypeEnum;
}

export interface GetStatsMemberRecapRequest {
    cust_id?: number;
    year?: GetStatsMemberRecapYearEnum;
    season?: number;
}

export interface GetStatsMemberRecentRacesRequest {
    cust_id?: number;
}

export interface GetStatsMemberSummaryRequest {
    cust_id?: number;
}

export interface GetStatsMemberYearlyRequest {
    cust_id?: number;
}

export interface GetStatsSeasonDriverStandingsRequest {
    season_id: number;
    car_class_id: number;
    division?: IracingDivision;
    race_week_num?: number;
}

export interface GetStatsSeasonQualifyResultsRequest {
    season_id: number;
    car_class_id: number;
    race_week_num: number;
    division?: IracingDivision;
}

export interface GetStatsSeasonSupersessionStandingsRequest {
    season_id: number;
    car_class_id: number;
    division?: IracingDivision;
    race_week_num?: number;
}

export interface GetStatsSeasonTeamStandingsRequest {
    season_id: number;
    car_class_id: number;
    race_week_num?: number;
}

export interface GetStatsSeasonTimeTrialResultsRequest {
    season_id: number;
    car_class_id: number;
    race_week_num: number;
    division?: IracingDivision;
}

export interface GetStatsSeasonTimeTrialStandingsRequest {
    season_id: number;
    car_class_id: number;
    division?: IracingDivision;
    race_week_num?: number;
}

export interface GetStatsWorldRecordsRequest {
    car_id: number;
    track_id: number;
    season_year?: number;
    season_quarter?: number;
}

/**
 * 
 */
export class StatsApi extends runtime.BaseAPI {

    /**
     */
    async getStatsMemberBestsRaw(requestParameters: GetStatsMemberBestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        if (requestParameters['car_id'] != null) {
            queryParameters['car_id'] = requestParameters['car_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/member_bests`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsMemberBests(requestParameters: GetStatsMemberBestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsMemberBestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsMemberCareerRaw(requestParameters: GetStatsMemberCareerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/member_career`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsMemberCareer(requestParameters: GetStatsMemberCareerRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsMemberCareerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsMemberDivisionRaw(requestParameters: GetStatsMemberDivisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getStatsMemberDivision().'
            );
        }

        if (requestParameters['event_type'] == null) {
            throw new runtime.RequiredError(
                'event_type',
                'Required parameter "event_type" was null or undefined when calling getStatsMemberDivision().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['event_type'] != null) {
            queryParameters['event_type'] = requestParameters['event_type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/member_division`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsMemberDivision(requestParameters: GetStatsMemberDivisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsMemberDivisionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsMemberRecapRaw(requestParameters: GetStatsMemberRecapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season'] = requestParameters['season'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/member_recap`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsMemberRecap(requestParameters: GetStatsMemberRecapRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsMemberRecapRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsMemberRecentRacesRaw(requestParameters: GetStatsMemberRecentRacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/member_recent_races`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsMemberRecentRaces(requestParameters: GetStatsMemberRecentRacesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsMemberRecentRacesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsMemberSummaryRaw(requestParameters: GetStatsMemberSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/member_summary`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsMemberSummary(requestParameters: GetStatsMemberSummaryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsMemberSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsMemberYearlyRaw(requestParameters: GetStatsMemberYearlyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cust_id'] != null) {
            queryParameters['cust_id'] = requestParameters['cust_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/member_yearly`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsMemberYearly(requestParameters: GetStatsMemberYearlyRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsMemberYearlyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsSeasonDriverStandingsRaw(requestParameters: GetStatsSeasonDriverStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getStatsSeasonDriverStandings().'
            );
        }

        if (requestParameters['car_class_id'] == null) {
            throw new runtime.RequiredError(
                'car_class_id',
                'Required parameter "car_class_id" was null or undefined when calling getStatsSeasonDriverStandings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['car_class_id'] != null) {
            queryParameters['car_class_id'] = requestParameters['car_class_id'];
        }

        if (requestParameters['division'] != null) {
            queryParameters['division'] = requestParameters['division'];
        }

        if (requestParameters['race_week_num'] != null) {
            queryParameters['race_week_num'] = requestParameters['race_week_num'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/season_driver_standings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsSeasonDriverStandings(requestParameters: GetStatsSeasonDriverStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsSeasonDriverStandingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsSeasonQualifyResultsRaw(requestParameters: GetStatsSeasonQualifyResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getStatsSeasonQualifyResults().'
            );
        }

        if (requestParameters['car_class_id'] == null) {
            throw new runtime.RequiredError(
                'car_class_id',
                'Required parameter "car_class_id" was null or undefined when calling getStatsSeasonQualifyResults().'
            );
        }

        if (requestParameters['race_week_num'] == null) {
            throw new runtime.RequiredError(
                'race_week_num',
                'Required parameter "race_week_num" was null or undefined when calling getStatsSeasonQualifyResults().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['car_class_id'] != null) {
            queryParameters['car_class_id'] = requestParameters['car_class_id'];
        }

        if (requestParameters['race_week_num'] != null) {
            queryParameters['race_week_num'] = requestParameters['race_week_num'];
        }

        if (requestParameters['division'] != null) {
            queryParameters['division'] = requestParameters['division'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/season_qualify_results`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsSeasonQualifyResults(requestParameters: GetStatsSeasonQualifyResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsSeasonQualifyResultsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsSeasonSupersessionStandingsRaw(requestParameters: GetStatsSeasonSupersessionStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getStatsSeasonSupersessionStandings().'
            );
        }

        if (requestParameters['car_class_id'] == null) {
            throw new runtime.RequiredError(
                'car_class_id',
                'Required parameter "car_class_id" was null or undefined when calling getStatsSeasonSupersessionStandings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['car_class_id'] != null) {
            queryParameters['car_class_id'] = requestParameters['car_class_id'];
        }

        if (requestParameters['division'] != null) {
            queryParameters['division'] = requestParameters['division'];
        }

        if (requestParameters['race_week_num'] != null) {
            queryParameters['race_week_num'] = requestParameters['race_week_num'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/season_supersession_standings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsSeasonSupersessionStandings(requestParameters: GetStatsSeasonSupersessionStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsSeasonSupersessionStandingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsSeasonTeamStandingsRaw(requestParameters: GetStatsSeasonTeamStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getStatsSeasonTeamStandings().'
            );
        }

        if (requestParameters['car_class_id'] == null) {
            throw new runtime.RequiredError(
                'car_class_id',
                'Required parameter "car_class_id" was null or undefined when calling getStatsSeasonTeamStandings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['car_class_id'] != null) {
            queryParameters['car_class_id'] = requestParameters['car_class_id'];
        }

        if (requestParameters['race_week_num'] != null) {
            queryParameters['race_week_num'] = requestParameters['race_week_num'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/season_team_standings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsSeasonTeamStandings(requestParameters: GetStatsSeasonTeamStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsSeasonTeamStandingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsSeasonTimeTrialResultsRaw(requestParameters: GetStatsSeasonTimeTrialResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getStatsSeasonTimeTrialResults().'
            );
        }

        if (requestParameters['car_class_id'] == null) {
            throw new runtime.RequiredError(
                'car_class_id',
                'Required parameter "car_class_id" was null or undefined when calling getStatsSeasonTimeTrialResults().'
            );
        }

        if (requestParameters['race_week_num'] == null) {
            throw new runtime.RequiredError(
                'race_week_num',
                'Required parameter "race_week_num" was null or undefined when calling getStatsSeasonTimeTrialResults().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['car_class_id'] != null) {
            queryParameters['car_class_id'] = requestParameters['car_class_id'];
        }

        if (requestParameters['race_week_num'] != null) {
            queryParameters['race_week_num'] = requestParameters['race_week_num'];
        }

        if (requestParameters['division'] != null) {
            queryParameters['division'] = requestParameters['division'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/season_time_trial_results`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsSeasonTimeTrialResults(requestParameters: GetStatsSeasonTimeTrialResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsSeasonTimeTrialResultsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsSeasonTimeTrialStandingsRaw(requestParameters: GetStatsSeasonTimeTrialStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['season_id'] == null) {
            throw new runtime.RequiredError(
                'season_id',
                'Required parameter "season_id" was null or undefined when calling getStatsSeasonTimeTrialStandings().'
            );
        }

        if (requestParameters['car_class_id'] == null) {
            throw new runtime.RequiredError(
                'car_class_id',
                'Required parameter "car_class_id" was null or undefined when calling getStatsSeasonTimeTrialStandings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['season_id'] != null) {
            queryParameters['season_id'] = requestParameters['season_id'];
        }

        if (requestParameters['car_class_id'] != null) {
            queryParameters['car_class_id'] = requestParameters['car_class_id'];
        }

        if (requestParameters['division'] != null) {
            queryParameters['division'] = requestParameters['division'];
        }

        if (requestParameters['race_week_num'] != null) {
            queryParameters['race_week_num'] = requestParameters['race_week_num'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/season_time_trial_standings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsSeasonTimeTrialStandings(requestParameters: GetStatsSeasonTimeTrialStandingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsSeasonTimeTrialStandingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStatsWorldRecordsRaw(requestParameters: GetStatsWorldRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['car_id'] == null) {
            throw new runtime.RequiredError(
                'car_id',
                'Required parameter "car_id" was null or undefined when calling getStatsWorldRecords().'
            );
        }

        if (requestParameters['track_id'] == null) {
            throw new runtime.RequiredError(
                'track_id',
                'Required parameter "track_id" was null or undefined when calling getStatsWorldRecords().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['car_id'] != null) {
            queryParameters['car_id'] = requestParameters['car_id'];
        }

        if (requestParameters['track_id'] != null) {
            queryParameters['track_id'] = requestParameters['track_id'];
        }

        if (requestParameters['season_year'] != null) {
            queryParameters['season_year'] = requestParameters['season_year'];
        }

        if (requestParameters['season_quarter'] != null) {
            queryParameters['season_quarter'] = requestParameters['season_quarter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/stats/world_records`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatsWorldRecords(requestParameters: GetStatsWorldRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getStatsWorldRecordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetStatsMemberDivisionEventTypeEnum = {
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type GetStatsMemberDivisionEventTypeEnum = typeof GetStatsMemberDivisionEventTypeEnum[keyof typeof GetStatsMemberDivisionEventTypeEnum];
/**
 * @export
 */
export const GetStatsMemberRecapYearEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type GetStatsMemberRecapYearEnum = typeof GetStatsMemberRecapYearEnum[keyof typeof GetStatsMemberRecapYearEnum];
