/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  IracingAPIResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IracingAPIResponseFromJSON,
    IracingAPIResponseToJSON,
} from '../models/index';

export interface GetTimeAttackMemberSeasonResultsRequest {
    ta_comp_season_id: number;
}

/**
 * 
 */
export class TimeAttackApi extends runtime.BaseAPI {

    /**
     */
    async getTimeAttackMemberSeasonResultsRaw(requestParameters: GetTimeAttackMemberSeasonResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IracingAPIResponse>> {
        if (requestParameters['ta_comp_season_id'] == null) {
            throw new runtime.RequiredError(
                'ta_comp_season_id',
                'Required parameter "ta_comp_season_id" was null or undefined when calling getTimeAttackMemberSeasonResults().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ta_comp_season_id'] != null) {
            queryParameters['ta_comp_season_id'] = requestParameters['ta_comp_season_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/data/time_attack/member_season_results`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IracingAPIResponseFromJSON(jsonValue));
    }

    /**
     */
    async getTimeAttackMemberSeasonResults(requestParameters: GetTimeAttackMemberSeasonResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IracingAPIResponse> {
        const response = await this.getTimeAttackMemberSeasonResultsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
