/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * iRacing Event Type
 * @export
 */
export const IracingEventType = {
    /**
    * Practice
    */
    NUMBER_2: 2,
    /**
    * Qualifying
    */
    NUMBER_3: 3,
    /**
    * Time trial
    */
    NUMBER_4: 4,
    /**
    * Race
    */
    NUMBER_5: 5
} as const;
export type IracingEventType = typeof IracingEventType[keyof typeof IracingEventType];


export function instanceOfIracingEventType(value: any): boolean {
    for (const key in IracingEventType) {
        if (Object.prototype.hasOwnProperty.call(IracingEventType, key)) {
            if (IracingEventType[key as keyof typeof IracingEventType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IracingEventTypeFromJSON(json: any): IracingEventType {
    return IracingEventTypeFromJSONTyped(json, false);
}

export function IracingEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IracingEventType {
    return json as IracingEventType;
}

export function IracingEventTypeToJSON(value?: IracingEventType | null): any {
    return value as any;
}

export function IracingEventTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): IracingEventType {
    return value as IracingEventType;
}

