/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Racing category.
 * @export
 */
export const IracingCategory = {
    /**
    * Oval discipline
    */
    Oval: 'oval',
    /**
    * Road discipline. Legacy, use &#x60;sports_car&#x60; or &#x60;formula_car&#x60; instead.
    */
    Road: 'road',
    /**
    * Dirt road discipline.
    */
    DirtRoad: 'dirt_road',
    /**
    * Dirt oval discipline.
    */
    DirtOval: 'dirt_oval',
    /**
    * Sports car discipline.
    */
    SportsCar: 'sports_car',
    /**
    * Formula car discipline.
    */
    FormulaCar: 'formula_car'
} as const;
export type IracingCategory = typeof IracingCategory[keyof typeof IracingCategory];


export function instanceOfIracingCategory(value: any): boolean {
    for (const key in IracingCategory) {
        if (Object.prototype.hasOwnProperty.call(IracingCategory, key)) {
            if (IracingCategory[key as keyof typeof IracingCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IracingCategoryFromJSON(json: any): IracingCategory {
    return IracingCategoryFromJSONTyped(json, false);
}

export function IracingCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IracingCategory {
    return json as IracingCategory;
}

export function IracingCategoryToJSON(value?: IracingCategory | null): any {
    return value as any;
}

export function IracingCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): IracingCategory {
    return value as IracingCategory;
}

