/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type IracingServiceMethodDocsNote
 *
 * @export
 */
export type IracingServiceMethodDocsNote = Array<string> | string;

export function IracingServiceMethodDocsNoteFromJSON(
  json: any,
): IracingServiceMethodDocsNote {
  return IracingServiceMethodDocsNoteFromJSONTyped(json, false);
}

export function IracingServiceMethodDocsNoteFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IracingServiceMethodDocsNote {
  if (json == null) {
    return json;
  }
  if (Array.isArray(json)) {
    if (json.every((item) => typeof item === "string")) {
      return json;
    }
  }
  if (typeof json === "string") {
    return json;
  }
  return {} as any;
}

export function IracingServiceMethodDocsNoteToJSON(json: any): any {
  return IracingServiceMethodDocsNoteToJSONTyped(json, false);
}

export function IracingServiceMethodDocsNoteToJSONTyped(
  value?: IracingServiceMethodDocsNote | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }
  if (Array.isArray(value)) {
    if (value.every((item) => typeof item === "string")) {
      return value;
    }
  }
  if (typeof value === "string") {
    return value;
  }
  return {};
}
