/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IracingServiceMethodParametersDocs } from './IracingServiceMethodParametersDocs';
import {
    IracingServiceMethodParametersDocsFromJSON,
    IracingServiceMethodParametersDocsFromJSONTyped,
    IracingServiceMethodParametersDocsToJSON,
    IracingServiceMethodParametersDocsToJSONTyped,
} from './IracingServiceMethodParametersDocs';

/**
 * An iRacing API Service Method object.
 * @export
 * @interface IracingServiceMethodDocs
 */
export interface IracingServiceMethodDocs {
    /**
     * 
     * @type {string}
     * @memberof IracingServiceMethodDocs
     */
    link: string;
    /**
     * 
     * @type {{ [key: string]: IracingServiceMethodParametersDocs; }}
     * @memberof IracingServiceMethodDocs
     */
    parameters: { [key: string]: IracingServiceMethodParametersDocs; };
    /**
     * 
     * @type {number}
     * @memberof IracingServiceMethodDocs
     */
    expirationSeconds?: number;
}

/**
 * Check if a given object implements the IracingServiceMethodDocs interface.
 */
export function instanceOfIracingServiceMethodDocs(value: object): value is IracingServiceMethodDocs {
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    return true;
}

export function IracingServiceMethodDocsFromJSON(json: any): IracingServiceMethodDocs {
    return IracingServiceMethodDocsFromJSONTyped(json, false);
}

export function IracingServiceMethodDocsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IracingServiceMethodDocs {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'],
        'parameters': (mapValues(json['parameters'], IracingServiceMethodParametersDocsFromJSON)),
        'expirationSeconds': json['expirationSeconds'] == null ? undefined : json['expirationSeconds'],
    };
}

export function IracingServiceMethodDocsToJSON(json: any): IracingServiceMethodDocs {
    return IracingServiceMethodDocsToJSONTyped(json, false);
}

export function IracingServiceMethodDocsToJSONTyped(value?: IracingServiceMethodDocs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'parameters': (mapValues(value['parameters'], IracingServiceMethodParametersDocsToJSON)),
        'expirationSeconds': value['expirationSeconds'],
    };
}

