/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An iRacing API Service Method Parameters object.
 * @export
 * @interface IracingServiceMethodParametersDocs
 */
export interface IracingServiceMethodParametersDocs {
    /**
     * 
     * @type {string}
     * @memberof IracingServiceMethodParametersDocs
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof IracingServiceMethodParametersDocs
     */
    note?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IracingServiceMethodParametersDocs
     */
    required?: boolean;
}

/**
 * Check if a given object implements the IracingServiceMethodParametersDocs interface.
 */
export function instanceOfIracingServiceMethodParametersDocs(value: object): value is IracingServiceMethodParametersDocs {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function IracingServiceMethodParametersDocsFromJSON(json: any): IracingServiceMethodParametersDocs {
    return IracingServiceMethodParametersDocsFromJSONTyped(json, false);
}

export function IracingServiceMethodParametersDocsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IracingServiceMethodParametersDocs {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'note': json['note'] == null ? undefined : json['note'],
        'required': json['required'] == null ? undefined : json['required'],
    };
}

export function IracingServiceMethodParametersDocsToJSON(json: any): IracingServiceMethodParametersDocs {
    return IracingServiceMethodParametersDocsToJSONTyped(json, false);
}

export function IracingServiceMethodParametersDocsToJSONTyped(value?: IracingServiceMethodParametersDocs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'note': value['note'],
        'required': value['required'],
    };
}

