/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response from iRacing `/data` API.
 * @export
 * @interface IracingAPIResponse
 */
export interface IracingAPIResponse {
    /**
     * A link to the cached data
     * @type {string}
     * @memberof IracingAPIResponse
     */
    link: string;
    /**
     * 
     * @type {Date}
     * @memberof IracingAPIResponse
     */
    expires: Date;
}

/**
 * Check if a given object implements the IracingAPIResponse interface.
 */
export function instanceOfIracingAPIResponse(value: object): value is IracingAPIResponse {
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('expires' in value) || value['expires'] === undefined) return false;
    return true;
}

export function IracingAPIResponseFromJSON(json: any): IracingAPIResponse {
    return IracingAPIResponseFromJSONTyped(json, false);
}

export function IracingAPIResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IracingAPIResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'],
        'expires': (new Date(json['expires'])),
    };
}

export function IracingAPIResponseToJSON(json: any): IracingAPIResponse {
    return IracingAPIResponseToJSONTyped(json, false);
}

export function IracingAPIResponseToJSONTyped(value?: IracingAPIResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'expires': value['expires'].toISOString(),
    };
}

