/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * iRacing Divisions. Divisions are 0-based: 0 is Division 1, 10 is Rookie. See /data/constants/divisons for more information.
 * @export
 */
export const IracingDivision = {
    /**
    * Division 1
    */
    NUMBER_0: 0,
    /**
    * Division 2
    */
    NUMBER_1: 1,
    /**
    * Division 3
    */
    NUMBER_2: 2,
    /**
    * Division 4
    */
    NUMBER_3: 3,
    /**
    * Division 5
    */
    NUMBER_4: 4,
    /**
    * Division 6
    */
    NUMBER_5: 5,
    /**
    * Division 7
    */
    NUMBER_6: 6,
    /**
    * Division 8
    */
    NUMBER_7: 7,
    /**
    * Division 9
    */
    NUMBER_8: 8,
    /**
    * Division 10
    */
    NUMBER_9: 9,
    /**
    * Rookie
    */
    NUMBER_10: 10
} as const;
export type IracingDivision = typeof IracingDivision[keyof typeof IracingDivision];


export function instanceOfIracingDivision(value: any): boolean {
    for (const key in IracingDivision) {
        if (Object.prototype.hasOwnProperty.call(IracingDivision, key)) {
            if (IracingDivision[key as keyof typeof IracingDivision] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IracingDivisionFromJSON(json: any): IracingDivision {
    return IracingDivisionFromJSONTyped(json, false);
}

export function IracingDivisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IracingDivision {
    return json as IracingDivision;
}

export function IracingDivisionToJSON(value?: IracingDivision | null): any {
    return value as any;
}

export function IracingDivisionToJSONTyped(value: any, ignoreDiscriminator: boolean): IracingDivision {
    return value as IracingDivision;
}

