/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { IracingServiceMethodParametersDocs } from "./IracingServiceMethodParametersDocs";
import {
  IracingServiceMethodParametersDocsFromJSON,
  IracingServiceMethodParametersDocsFromJSONTyped,
  IracingServiceMethodParametersDocsToJSON,
  IracingServiceMethodParametersDocsToJSONTyped,
} from "./IracingServiceMethodParametersDocs";
import type { IracingServiceMethodDocsNote } from "./IracingServiceMethodDocsNote";
import {
  IracingServiceMethodDocsNoteFromJSON,
  IracingServiceMethodDocsNoteFromJSONTyped,
  IracingServiceMethodDocsNoteToJSON,
  IracingServiceMethodDocsNoteToJSONTyped,
} from "./IracingServiceMethodDocsNote";

/**
 * An iRacing API Service Method object.
 * @export
 * @interface IracingServiceMethodDocs
 */
export interface IracingServiceMethodDocs {
  /**
   *
   * @type {string}
   * @memberof IracingServiceMethodDocs
   */
  link: string;
  /**
   *
   * @type {{ [key: string]: IracingServiceMethodParametersDocs; }}
   * @memberof IracingServiceMethodDocs
   */
  parameters?: { [key: string]: IracingServiceMethodParametersDocs };
  /**
   *
   * @type {IracingServiceMethodDocsNote}
   * @memberof IracingServiceMethodDocs
   */
  note?: IracingServiceMethodDocsNote;
  /**
   *
   * @type {number}
   * @memberof IracingServiceMethodDocs
   */
  expirationSeconds?: number;
}

/**
 * Check if a given object implements the IracingServiceMethodDocs interface.
 */
export function instanceOfIracingServiceMethodDocs(
  value: object,
): value is IracingServiceMethodDocs {
  if (!("link" in value) || value["link"] === undefined) return false;
  return true;
}

export function IracingServiceMethodDocsFromJSON(
  json: any,
): IracingServiceMethodDocs {
  return IracingServiceMethodDocsFromJSONTyped(json, false);
}

export function IracingServiceMethodDocsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IracingServiceMethodDocs {
  if (json == null) {
    return json;
  }
  return {
    link: json["link"],
    parameters:
      json["parameters"] == null
        ? undefined
        : mapValues(
            json["parameters"],
            IracingServiceMethodParametersDocsFromJSON,
          ),
    note:
      json["note"] == null
        ? undefined
        : IracingServiceMethodDocsNoteFromJSON(json["note"]),
    expirationSeconds:
      json["expirationSeconds"] == null ? undefined : json["expirationSeconds"],
  };
}

export function IracingServiceMethodDocsToJSON(
  json: any,
): IracingServiceMethodDocs {
  return IracingServiceMethodDocsToJSONTyped(json, false);
}

export function IracingServiceMethodDocsToJSONTyped(
  value?: IracingServiceMethodDocs | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    link: value["link"],
    parameters:
      value["parameters"] == null
        ? undefined
        : mapValues(
            value["parameters"],
            IracingServiceMethodParametersDocsToJSON,
          ),
    note: IracingServiceMethodDocsNoteToJSON(value["note"]),
    expirationSeconds: value["expirationSeconds"],
  };
}
