/* tslint:disable */
/* eslint-disable */
/**
 * iRacing `/data` API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAuthRequest
 */
export interface PostAuthRequest {
    /**
     * 
     * @type {string}
     * @memberof PostAuthRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PostAuthRequest
     */
    password: string;
}

/**
 * Check if a given object implements the PostAuthRequest interface.
 */
export function instanceOfPostAuthRequest(value: object): value is PostAuthRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PostAuthRequestFromJSON(json: any): PostAuthRequest {
    return PostAuthRequestFromJSONTyped(json, false);
}

export function PostAuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAuthRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function PostAuthRequestToJSON(json: any): PostAuthRequest {
    return PostAuthRequestToJSONTyped(json, false);
}

export function PostAuthRequestToJSONTyped(value?: PostAuthRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

