/*
 * iRacing `/data` API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`get_league`]
#[derive(Clone, Debug)]
pub struct GetLeagueParams {
    pub league_id: f64,
    /// For faster responses, only request when necessary.
    pub include_licenses: Option<bool>
}

/// struct for passing parameters to the method [`get_league_customer_league_sessions`]
#[derive(Clone, Debug)]
pub struct GetLeagueCustomerLeagueSessionsParams {
    /// If true, return only sessions created by this user.
    pub mine: Option<bool>,
    /// If set, return only sessions using this car or track package ID.
    pub package_id: Option<f64>
}

/// struct for passing parameters to the method [`get_league_directory`]
#[derive(Clone, Debug)]
pub struct GetLeagueDirectoryParams {
    /// Will search against league name, description, owner, and league ID.
    pub search: Option<String>,
    /// One or more tags, comma-separated.
    pub tag: Option<String>,
    /// If true include only leagues for which customer is a member.
    pub restrict_to_member: Option<bool>,
    /// If true include only leagues which are recruiting.
    pub restrict_to_recruiting: Option<bool>,
    /// If true include only leagues owned by a friend.
    pub restrict_to_friends: Option<bool>,
    /// If true include only leagues owned by a watched member.
    pub restrict_to_watched: Option<bool>,
    /// If set include leagues with at least this number of members.
    pub minimum_roster_count: Option<f64>,
    /// If set include leagues with no more than this number of members.
    pub maximum_roster_count: Option<f64>,
    /// First row of results to return.  Defaults to 1.
    pub lowerbound: Option<f64>,
    /// Last row of results to return. Defaults to lowerbound + 39.
    pub upperbound: Option<f64>,
    /// One of relevance, leaguename, displayname, rostercount. displayname is owners's name. Defaults to relevance.
    pub sort: Option<String>,
    /// One of asc or desc.  Defaults to asc.
    pub order: Option<String>
}

/// struct for passing parameters to the method [`get_league_membership`]
#[derive(Clone, Debug)]
pub struct GetLeagueMembershipParams {
    /// If different from the authenticated member, the following restrictions apply: - Caller cannot be on requested customer's block list or an empty list will result; - Requested customer cannot have their online activity preference set to hidden or an empty list will result; - Only leagues for which the requested customer is an admin and the league roster is not private are returned.
    pub cust_id: Option<f64>,
    pub include_league: Option<bool>
}

/// struct for passing parameters to the method [`get_league_points_systems`]
#[derive(Clone, Debug)]
pub struct GetLeaguePointsSystemsParams {
    pub league_id: f64,
    /// If included and the season is using custom points (points_system_id:2) then the custom points option is included in the returned list. Otherwise the custom points option is not returned.
    pub season_id: Option<f64>
}

/// struct for passing parameters to the method [`get_league_roster`]
#[derive(Clone, Debug)]
pub struct GetLeagueRosterParams {
    pub league_id: f64,
    /// For faster responses, only request when necessary.
    pub include_licenses: Option<bool>
}

/// struct for passing parameters to the method [`get_league_season_sessions`]
#[derive(Clone, Debug)]
pub struct GetLeagueSeasonSessionsParams {
    pub league_id: f64,
    pub season_id: f64,
    /// If true include only sessions for which results are available.
    pub results_only: Option<bool>
}

/// struct for passing parameters to the method [`get_league_season_standings`]
#[derive(Clone, Debug)]
pub struct GetLeagueSeasonStandingsParams {
    pub league_id: f64,
    pub season_id: f64,
    pub car_class_id: Option<f64>,
    /// If car_class_id is included then the standings are for the car in that car class, otherwise they are for the car across car classes.
    pub car_id: Option<f64>
}

/// struct for passing parameters to the method [`get_league_seasons`]
#[derive(Clone, Debug)]
pub struct GetLeagueSeasonsParams {
    pub league_id: f64,
    /// If true include seasons which are no longer active.
    pub retired: Option<bool>
}


/// struct for typed errors of method [`get_league`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeagueError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_league_customer_league_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeagueCustomerLeagueSessionsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_league_directory`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeagueDirectoryError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_league_membership`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeagueMembershipError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_league_points_systems`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeaguePointsSystemsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_league_roster`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeagueRosterError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_league_season_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeagueSeasonSessionsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_league_season_standings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeagueSeasonStandingsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_league_seasons`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeagueSeasonsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


pub async fn get_league(configuration: &configuration::Configuration, params: GetLeagueParams) -> Result<models::IracingApiResponse, Error<GetLeagueError>> {

    let uri_str = format!("{}/data/league/get", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("league_id", &params.league_id.to_string())]);
    if let Some(ref param_value) = params.include_licenses {
        req_builder = req_builder.query(&[("include_licenses", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeagueError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_league_customer_league_sessions(configuration: &configuration::Configuration, params: GetLeagueCustomerLeagueSessionsParams) -> Result<models::IracingApiResponse, Error<GetLeagueCustomerLeagueSessionsError>> {

    let uri_str = format!("{}/data/league/cust_league_sessions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.mine {
        req_builder = req_builder.query(&[("mine", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.package_id {
        req_builder = req_builder.query(&[("package_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeagueCustomerLeagueSessionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_league_directory(configuration: &configuration::Configuration, params: GetLeagueDirectoryParams) -> Result<models::IracingApiResponse, Error<GetLeagueDirectoryError>> {

    let uri_str = format!("{}/data/league/directory", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.search {
        req_builder = req_builder.query(&[("search", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.tag {
        req_builder = req_builder.query(&[("tag", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.restrict_to_member {
        req_builder = req_builder.query(&[("restrict_to_member", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.restrict_to_recruiting {
        req_builder = req_builder.query(&[("restrict_to_recruiting", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.restrict_to_friends {
        req_builder = req_builder.query(&[("restrict_to_friends", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.restrict_to_watched {
        req_builder = req_builder.query(&[("restrict_to_watched", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.minimum_roster_count {
        req_builder = req_builder.query(&[("minimum_roster_count", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.maximum_roster_count {
        req_builder = req_builder.query(&[("maximum_roster_count", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.lowerbound {
        req_builder = req_builder.query(&[("lowerbound", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.upperbound {
        req_builder = req_builder.query(&[("upperbound", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeagueDirectoryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_league_membership(configuration: &configuration::Configuration, params: GetLeagueMembershipParams) -> Result<models::IracingApiResponse, Error<GetLeagueMembershipError>> {

    let uri_str = format!("{}/data/league/membership", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cust_id {
        req_builder = req_builder.query(&[("cust_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.include_league {
        req_builder = req_builder.query(&[("include_league", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeagueMembershipError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_league_points_systems(configuration: &configuration::Configuration, params: GetLeaguePointsSystemsParams) -> Result<models::IracingApiResponse, Error<GetLeaguePointsSystemsError>> {

    let uri_str = format!("{}/data/league/get_points_systems", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("league_id", &params.league_id.to_string())]);
    if let Some(ref param_value) = params.season_id {
        req_builder = req_builder.query(&[("season_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeaguePointsSystemsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_league_roster(configuration: &configuration::Configuration, params: GetLeagueRosterParams) -> Result<models::IracingApiResponse, Error<GetLeagueRosterError>> {

    let uri_str = format!("{}/data/league/roster", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("league_id", &params.league_id.to_string())]);
    if let Some(ref param_value) = params.include_licenses {
        req_builder = req_builder.query(&[("include_licenses", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeagueRosterError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_league_season_sessions(configuration: &configuration::Configuration, params: GetLeagueSeasonSessionsParams) -> Result<models::IracingApiResponse, Error<GetLeagueSeasonSessionsError>> {

    let uri_str = format!("{}/data/league/season_sessions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("league_id", &params.league_id.to_string())]);
    req_builder = req_builder.query(&[("season_id", &params.season_id.to_string())]);
    if let Some(ref param_value) = params.results_only {
        req_builder = req_builder.query(&[("results_only", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeagueSeasonSessionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_league_season_standings(configuration: &configuration::Configuration, params: GetLeagueSeasonStandingsParams) -> Result<models::IracingApiResponse, Error<GetLeagueSeasonStandingsError>> {

    let uri_str = format!("{}/data/league/season_standings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("league_id", &params.league_id.to_string())]);
    req_builder = req_builder.query(&[("season_id", &params.season_id.to_string())]);
    if let Some(ref param_value) = params.car_class_id {
        req_builder = req_builder.query(&[("car_class_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.car_id {
        req_builder = req_builder.query(&[("car_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeagueSeasonStandingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_league_seasons(configuration: &configuration::Configuration, params: GetLeagueSeasonsParams) -> Result<models::IracingApiResponse, Error<GetLeagueSeasonsError>> {

    let uri_str = format!("{}/data/league/seasons", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("league_id", &params.league_id.to_string())]);
    if let Some(ref param_value) = params.retired {
        req_builder = req_builder.query(&[("retired", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeagueSeasonsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

