/*
 * iRacing `/data` API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`get_stats_member_bests`]
#[derive(Clone, Debug)]
pub struct GetStatsMemberBestsParams {
    /// Defaults to the authenticated member.
    pub cust_id: Option<f64>,
    /// First call should exclude car_id; use cars_driven list in return for subsequent calls.
    pub car_id: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_member_career`]
#[derive(Clone, Debug)]
pub struct GetStatsMemberCareerParams {
    /// Defaults to the authenticated member.
    pub cust_id: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_member_division`]
#[derive(Clone, Debug)]
pub struct GetStatsMemberDivisionParams {
    pub season_id: f64,
    /// The event type code for the division type: 4 - Time Trial; 5 - Race
    pub event_type: f64
}

/// struct for passing parameters to the method [`get_stats_member_recap`]
#[derive(Clone, Debug)]
pub struct GetStatsMemberRecapParams {
    /// Defaults to the authenticated member.
    pub cust_id: Option<f64>,
    /// Season year; if not supplied the current calendar year (UTC) is used.
    pub year: Option<f64>,
    /// Season (quarter) within the year; if not supplied the recap will be for the entire year.
    pub season: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_member_recent_races`]
#[derive(Clone, Debug)]
pub struct GetStatsMemberRecentRacesParams {
    /// Defaults to the authenticated member.
    pub cust_id: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_member_summary`]
#[derive(Clone, Debug)]
pub struct GetStatsMemberSummaryParams {
    /// Defaults to the authenticated member.
    pub cust_id: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_member_yearly`]
#[derive(Clone, Debug)]
pub struct GetStatsMemberYearlyParams {
    /// Defaults to the authenticated member.
    pub cust_id: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_season_driver_standings`]
#[derive(Clone, Debug)]
pub struct GetStatsSeasonDriverStandingsParams {
    pub season_id: f64,
    pub car_class_id: f64,
    pub division: Option<models::IracingDivision>,
    /// The first race week of a season is 0.
    pub race_week_num: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_season_qualify_results`]
#[derive(Clone, Debug)]
pub struct GetStatsSeasonQualifyResultsParams {
    pub season_id: f64,
    pub car_class_id: f64,
    /// The first race week of a season is 0.
    pub race_week_num: f64,
    pub division: Option<models::IracingDivision>
}

/// struct for passing parameters to the method [`get_stats_season_supersession_standings`]
#[derive(Clone, Debug)]
pub struct GetStatsSeasonSupersessionStandingsParams {
    pub season_id: f64,
    pub car_class_id: f64,
    pub division: Option<models::IracingDivision>,
    /// The first race week of a season is 0.
    pub race_week_num: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_season_team_standings`]
#[derive(Clone, Debug)]
pub struct GetStatsSeasonTeamStandingsParams {
    pub season_id: f64,
    pub car_class_id: f64,
    /// The first race week of a season is 0.
    pub race_week_num: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_season_time_trial_results`]
#[derive(Clone, Debug)]
pub struct GetStatsSeasonTimeTrialResultsParams {
    pub season_id: f64,
    pub car_class_id: f64,
    /// The first race week of a season is 0.
    pub race_week_num: f64,
    pub division: Option<models::IracingDivision>
}

/// struct for passing parameters to the method [`get_stats_season_time_trial_standings`]
#[derive(Clone, Debug)]
pub struct GetStatsSeasonTimeTrialStandingsParams {
    pub season_id: f64,
    pub car_class_id: f64,
    pub division: Option<models::IracingDivision>,
    /// The first race week of a season is 0.
    pub race_week_num: Option<f64>
}

/// struct for passing parameters to the method [`get_stats_world_records`]
#[derive(Clone, Debug)]
pub struct GetStatsWorldRecordsParams {
    pub car_id: f64,
    pub track_id: f64,
    /// Limit best times to a given year.
    pub season_year: Option<f64>,
    /// Limit best times to a given quarter; only applicable when year is used.
    pub season_quarter: Option<f64>
}


/// struct for typed errors of method [`get_stats_member_bests`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsMemberBestsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_member_career`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsMemberCareerError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_member_division`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsMemberDivisionError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_member_recap`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsMemberRecapError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_member_recent_races`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsMemberRecentRacesError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_member_summary`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsMemberSummaryError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_member_yearly`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsMemberYearlyError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_season_driver_standings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsSeasonDriverStandingsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_season_qualify_results`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsSeasonQualifyResultsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_season_supersession_standings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsSeasonSupersessionStandingsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_season_team_standings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsSeasonTeamStandingsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_season_time_trial_results`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsSeasonTimeTrialResultsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_season_time_trial_standings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsSeasonTimeTrialStandingsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_stats_world_records`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatsWorldRecordsError {
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


pub async fn get_stats_member_bests(configuration: &configuration::Configuration, params: GetStatsMemberBestsParams) -> Result<models::IracingApiResponse, Error<GetStatsMemberBestsError>> {

    let uri_str = format!("{}/data/stats/member_bests", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cust_id {
        req_builder = req_builder.query(&[("cust_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.car_id {
        req_builder = req_builder.query(&[("car_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsMemberBestsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_member_career(configuration: &configuration::Configuration, params: GetStatsMemberCareerParams) -> Result<models::IracingApiResponse, Error<GetStatsMemberCareerError>> {

    let uri_str = format!("{}/data/stats/member_career", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cust_id {
        req_builder = req_builder.query(&[("cust_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsMemberCareerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_member_division(configuration: &configuration::Configuration, params: GetStatsMemberDivisionParams) -> Result<models::IracingApiResponse, Error<GetStatsMemberDivisionError>> {

    let uri_str = format!("{}/data/stats/member_division", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("season_id", &params.season_id.to_string())]);
    req_builder = req_builder.query(&[("event_type", &params.event_type.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsMemberDivisionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_member_recap(configuration: &configuration::Configuration, params: GetStatsMemberRecapParams) -> Result<models::IracingApiResponse, Error<GetStatsMemberRecapError>> {

    let uri_str = format!("{}/data/stats/member_recap", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cust_id {
        req_builder = req_builder.query(&[("cust_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.season {
        req_builder = req_builder.query(&[("season", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsMemberRecapError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_member_recent_races(configuration: &configuration::Configuration, params: GetStatsMemberRecentRacesParams) -> Result<models::IracingApiResponse, Error<GetStatsMemberRecentRacesError>> {

    let uri_str = format!("{}/data/stats/member_recent_races", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cust_id {
        req_builder = req_builder.query(&[("cust_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsMemberRecentRacesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_member_summary(configuration: &configuration::Configuration, params: GetStatsMemberSummaryParams) -> Result<models::IracingApiResponse, Error<GetStatsMemberSummaryError>> {

    let uri_str = format!("{}/data/stats/member_summary", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cust_id {
        req_builder = req_builder.query(&[("cust_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsMemberSummaryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_member_yearly(configuration: &configuration::Configuration, params: GetStatsMemberYearlyParams) -> Result<models::IracingApiResponse, Error<GetStatsMemberYearlyError>> {

    let uri_str = format!("{}/data/stats/member_yearly", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cust_id {
        req_builder = req_builder.query(&[("cust_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsMemberYearlyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_season_driver_standings(configuration: &configuration::Configuration, params: GetStatsSeasonDriverStandingsParams) -> Result<models::IracingApiResponse, Error<GetStatsSeasonDriverStandingsError>> {

    let uri_str = format!("{}/data/stats/season_driver_standings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("season_id", &params.season_id.to_string())]);
    req_builder = req_builder.query(&[("car_class_id", &params.car_class_id.to_string())]);
    if let Some(ref param_value) = params.division {
        req_builder = req_builder.query(&[("division", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.race_week_num {
        req_builder = req_builder.query(&[("race_week_num", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsSeasonDriverStandingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_season_qualify_results(configuration: &configuration::Configuration, params: GetStatsSeasonQualifyResultsParams) -> Result<models::IracingApiResponse, Error<GetStatsSeasonQualifyResultsError>> {

    let uri_str = format!("{}/data/stats/season_qualify_results", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("season_id", &params.season_id.to_string())]);
    req_builder = req_builder.query(&[("car_class_id", &params.car_class_id.to_string())]);
    req_builder = req_builder.query(&[("race_week_num", &params.race_week_num.to_string())]);
    if let Some(ref param_value) = params.division {
        req_builder = req_builder.query(&[("division", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsSeasonQualifyResultsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_season_supersession_standings(configuration: &configuration::Configuration, params: GetStatsSeasonSupersessionStandingsParams) -> Result<models::IracingApiResponse, Error<GetStatsSeasonSupersessionStandingsError>> {

    let uri_str = format!("{}/data/stats/season_supersession_standings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("season_id", &params.season_id.to_string())]);
    req_builder = req_builder.query(&[("car_class_id", &params.car_class_id.to_string())]);
    if let Some(ref param_value) = params.division {
        req_builder = req_builder.query(&[("division", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.race_week_num {
        req_builder = req_builder.query(&[("race_week_num", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsSeasonSupersessionStandingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_season_team_standings(configuration: &configuration::Configuration, params: GetStatsSeasonTeamStandingsParams) -> Result<models::IracingApiResponse, Error<GetStatsSeasonTeamStandingsError>> {

    let uri_str = format!("{}/data/stats/season_team_standings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("season_id", &params.season_id.to_string())]);
    req_builder = req_builder.query(&[("car_class_id", &params.car_class_id.to_string())]);
    if let Some(ref param_value) = params.race_week_num {
        req_builder = req_builder.query(&[("race_week_num", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsSeasonTeamStandingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_season_time_trial_results(configuration: &configuration::Configuration, params: GetStatsSeasonTimeTrialResultsParams) -> Result<models::IracingApiResponse, Error<GetStatsSeasonTimeTrialResultsError>> {

    let uri_str = format!("{}/data/stats/season_time_trial_results", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("season_id", &params.season_id.to_string())]);
    req_builder = req_builder.query(&[("car_class_id", &params.car_class_id.to_string())]);
    req_builder = req_builder.query(&[("race_week_num", &params.race_week_num.to_string())]);
    if let Some(ref param_value) = params.division {
        req_builder = req_builder.query(&[("division", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsSeasonTimeTrialResultsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_season_time_trial_standings(configuration: &configuration::Configuration, params: GetStatsSeasonTimeTrialStandingsParams) -> Result<models::IracingApiResponse, Error<GetStatsSeasonTimeTrialStandingsError>> {

    let uri_str = format!("{}/data/stats/season_time_trial_standings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("season_id", &params.season_id.to_string())]);
    req_builder = req_builder.query(&[("car_class_id", &params.car_class_id.to_string())]);
    if let Some(ref param_value) = params.division {
        req_builder = req_builder.query(&[("division", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.race_week_num {
        req_builder = req_builder.query(&[("race_week_num", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsSeasonTimeTrialStandingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_stats_world_records(configuration: &configuration::Configuration, params: GetStatsWorldRecordsParams) -> Result<models::IracingApiResponse, Error<GetStatsWorldRecordsError>> {

    let uri_str = format!("{}/data/stats/world_records", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("car_id", &params.car_id.to_string())]);
    req_builder = req_builder.query(&[("track_id", &params.track_id.to_string())]);
    if let Some(ref param_value) = params.season_year {
        req_builder = req_builder.query(&[("season_year", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.season_quarter {
        req_builder = req_builder.query(&[("season_quarter", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IracingApiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IracingApiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatsWorldRecordsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

