/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The session string from the iRacing Simulation.
 */
export interface Session {
  WeekendInfo: {
    TrackName: string;
    TrackID: number;
    TrackLength: string;
    TrackLengthOfficial: string;
    TrackDisplayName: string;
    TrackDisplayShortName: string;
    TrackConfigName: string;
    TrackCity: string;
    TrackState: string;
    TrackCountry: string;
    TrackAltitude: string;
    TrackLatitude: string;
    TrackLongitude: string;
    TrackNorthOffset: string;
    TrackNumTurns: number;
    TrackPitSpeedLimit: string;
    TrackPaceSpeed: string;
    TrackNumPitStalls: number;
    TrackType: string;
    TrackDirection: string;
    TrackWeatherType: string;
    TrackSkies: string;
    TrackSurfaceTemp: string;
    TrackSurfaceTempCrew: string;
    TrackAirTemp: string;
    TrackAirPressure: string;
    TrackAirDensity: string;
    TrackWindVel: string;
    TrackWindDir: string;
    TrackRelativeHumidity: string;
    TrackFogLevel: string;
    TrackPrecipitation: string;
    TrackCleanup: number;
    TrackDynamicTrack: number;
    TrackVersion: string;
    SeriesID: number;
    SeasonID: number;
    SessionID: number;
    SubSessionID: number;
    LeagueID: number;
    Official: number;
    RaceWeek: number;
    EventType: string;
    Category: string;
    SimMode: string;
    TeamRacing: number;
    MinDrivers: number;
    MaxDrivers: number;
    DCRuleSet: string;
    QualifierMustStartRace: number;
    NumCarClasses: number;
    NumCarTypes: number;
    HeatRacing: number;
    BuildType: string;
    BuildTarget: string;
    BuildVersion: string;
    RaceFarm: string;
    WeekendOptions: {
      NumStarters: number;
      StartingGrid: string;
      QualifyScoring: string;
      CourseCautions: string;
      StandingStart: number;
      ShortParadeLap: number;
      Restarts: string;
      WeatherType: string;
      Skies: string;
      WindDirection: string;
      WindSpeed: string;
      WeatherTemp: string;
      RelativeHumidity: string;
      FogLevel: string;
      TimeOfDay: string;
      Date: string;
      EarthRotationSpeedupFactor: number;
      Unofficial: number;
      CommercialMode: string;
      NightMode: string;
      IsFixedSetup: number;
      StrictLapsChecking: string;
      HasOpenRegistration: number;
      HardcoreLevel: number;
      NumJokerLaps: number;
      IncidentLimit: number;
      FastRepairsLimit: number;
      GreenWhiteCheckeredLimit: number;
    };
    TelemetryOptions: {
      TelemetryDiskFile: string;
    };
  };
  SessionInfo: {
    CurrentSessionNum: number;
    Sessions: {
      SessionNum: number;
      SessionLaps: number | string;
      SessionTime: string;
      SessionNumLapsToAvg: number;
      SessionType: string;
      SessionTrackRubberState: string;
      SessionName: string;
      SessionSubType: null;
      SessionSkipped: number;
      SessionRunGroupsUsed: number;
      SessionEnforceTireCompoundChange: number;
      ResultsPositions: {
        Position: number;
        ClassPosition: number;
        CarIdx: number;
        Lap: number;
        Time: number;
        FastestLap: number;
        FastestTime: number;
        LastTime: number;
        LapsLed: number;
        LapsComplete: number;
        JokerLapsComplete: number;
        LapsDriven: number;
        Incidents: number;
        ReasonOutId: number;
        ReasonOutStr: string;
      }[];
      ResultsFastestLap: {
        CarIdx: number;
        FastestLap: number;
        FastestTime: number;
      }[];
      ResultsAverageLapTime: number;
      ResultsNumCautionFlags: number;
      ResultsNumCautionLaps: number;
      ResultsNumLeadChanges: number;
      ResultsLapsComplete: number;
      ResultsOfficial: number;
    }[];
  };
  QualifyResultsInfo: {
    Results: {
      Position: number;
      ClassPosition: number;
      CarIdx: number;
      FastestLap: number;
      FastestTime: number;
    }[];
  };
  CameraInfo: {
    Groups: {
      GroupNum: number;
      GroupName: string;
      Cameras: {
        CameraNum: number;
        CameraName: string;
      }[];
      IsScenic?: boolean;
    }[];
  };
  RadioInfo: {
    SelectedRadioNum: number;
    Radios: {
      RadioNum: number;
      HopCount: number;
      NumFrequencies: number;
      TunedToFrequencyNum: number;
      ScanningIsOn: number;
      Frequencies: {
        FrequencyNum: number;
        FrequencyName: string;
        Priority: number;
        CarIdx: number;
        EntryIdx: number;
        ClubID: number;
        CanScan: number;
        CanSquawk: number;
        Muted: number;
        IsMutable: number;
        IsDeletable: number;
      }[];
    }[];
  };
  DriverInfo: {
    DriverCarIdx: number;
    DriverUserID: number;
    PaceCarIdx: number;
    DriverHeadPosX: number;
    DriverHeadPosY: number;
    DriverHeadPosZ: number;
    DriverCarIsElectric: number;
    DriverCarIdleRPM: number;
    DriverCarRedLine: number;
    DriverCarEngCylinderCount: number;
    DriverCarFuelKgPerLtr: number;
    DriverCarFuelMaxLtr: number;
    DriverCarMaxFuelPct: number;
    DriverCarGearNumForward: number;
    DriverCarGearNeutral: number;
    DriverCarGearReverse: number;
    DriverCarSLFirstRPM: number;
    DriverCarSLShiftRPM: number;
    DriverCarSLLastRPM: number;
    DriverCarSLBlinkRPM: number;
    DriverCarVersion: string;
    DriverPitTrkPct: number;
    DriverCarEstLapTime: number;
    DriverSetupName: string;
    DriverSetupIsModified: number;
    DriverSetupLoadTypeName: string;
    DriverSetupPassedTech: number;
    DriverIncidentCount: number;
    DriverBrakeCurvingFactor: number;
    Drivers: {
      CarIdx: number;
      UserName: string;
      AbbrevName: null | string;
      Initials: null | string;
      UserID: number;
      TeamID: number;
      TeamName: string;
      CarNumber: string;
      CarNumberRaw: number;
      CarPath: string;
      CarClassID: number;
      CarID: number;
      CarIsPaceCar: number;
      CarIsAI: number;
      CarIsElectric: number;
      CarScreenName: string;
      CarScreenNameShort: string;
      CarClassShortName: null | string;
      CarClassRelSpeed: number;
      CarClassLicenseLevel: number;
      CarClassMaxFuelPct: string;
      CarClassWeightPenalty: string;
      CarClassPowerAdjust: string;
      CarClassDryTireSetLimit: string;
      CarClassColor: number;
      CarClassEstLapTime: number;
      IRating: number;
      LicString: string;
      IsSpectator: number;
      CarDesignStr: string;
      HelmetDesignStr: string;
      SuitDesignStr: string;
      BodyType: number;
      FaceType: number;
      HelmetType: number;
      CarNumberDesignStr: string;
      CarSponsor_1: number;
      CarSponsor_2: number;
      ClubName: string;
      ClubID: number;
      DivisionName: string;
      DivisionID: number;
      CurDriverIncidentCount: number;
      TeamIncidentCount: number;
    }[];
  };
  SplitTimeInfo: {
    Sectors: {
      SectorNum: number;
      SectorStartPct: number;
    }[];
  };
  CarSetup: {
    UpdateCount: number;
    Tires: {
      TireType: {
        TireType: string;
      };
      LeftFront: {
        StartingPressure: string;
        LastHotPressure: string;
        LastTempsOMI: string;
        TreadRemaining: string;
      };
      LeftRear: {
        StartingPressure: string;
        LastHotPressure: string;
        LastTempsOMI: string;
        TreadRemaining: string;
      };
      RightFront: {
        StartingPressure: string;
        LastHotPressure: string;
        LastTempsIMO: string;
        TreadRemaining: string;
      };
      RightRear: {
        StartingPressure: string;
        LastHotPressure: string;
        LastTempsIMO: string;
        TreadRemaining: string;
      };
    };
    Chassis: {
      Front: {
        ArbSetting: number;
        ToeIn: string;
        CrossWeight: string;
        NoseWeight: string;
      };
      LeftFront: {
        CornerWeight: string;
        RideHeight: string;
        SpringRate: string;
        SpringPerchOffset: string;
        BumpStiffness: string;
        ReboundStiffness: string;
        Camber: string;
      };
      LeftRear: {
        CornerWeight: string;
        RideHeight: string;
        SpringPerchOffset: string;
        BumpStiffness: string;
        ReboundStiffness: string;
        Camber: string;
        ToeIn: string;
      };
      InCarDials: {
        DashDisplayPage: string;
        BrakePressureBias: string;
        BrakePads: string;
        AbsSetting: string;
        TcSetting: string;
      };
      RightFront: {
        CornerWeight: string;
        RideHeight: string;
        SpringRate: string;
        SpringPerchOffset: string;
        BumpStiffness: string;
        ReboundStiffness: string;
        Camber: string;
      };
      RightRear: {
        CornerWeight: string;
        RideHeight: string;
        SpringPerchOffset: string;
        BumpStiffness: string;
        ReboundStiffness: string;
        Camber: string;
        ToeIn: string;
      };
      Rear: {
        FuelLevel: string;
        ArbSetting: number;
        WingSetting: number;
        DiffClutches: number;
      };
    };
  };
}
