/* tslint:disable */
/* eslint-disable */
/**
 * iRacing OAuth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IracingProfileGet200Response
 */
export interface IracingProfileGet200Response {
    /**
     * 
     * @type {string}
     * @memberof IracingProfileGet200Response
     */
    iracingName: string;
    /**
     * 
     * @type {number}
     * @memberof IracingProfileGet200Response
     */
    iracingCustId: number;
}

/**
 * Check if a given object implements the IracingProfileGet200Response interface.
 */
export function instanceOfIracingProfileGet200Response(value: object): value is IracingProfileGet200Response {
    if (!('iracingName' in value) || value['iracingName'] === undefined) return false;
    if (!('iracingCustId' in value) || value['iracingCustId'] === undefined) return false;
    return true;
}

export function IracingProfileGet200ResponseFromJSON(json: any): IracingProfileGet200Response {
    return IracingProfileGet200ResponseFromJSONTyped(json, false);
}

export function IracingProfileGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IracingProfileGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'iracingName': json['iracing_name'],
        'iracingCustId': json['iracing_cust_id'],
    };
}

export function IracingProfileGet200ResponseToJSON(json: any): IracingProfileGet200Response {
    return IracingProfileGet200ResponseToJSONTyped(json, false);
}

export function IracingProfileGet200ResponseToJSONTyped(value?: IracingProfileGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iracing_name': value['iracingName'],
        'iracing_cust_id': value['iracingCustId'],
    };
}

