/* tslint:disable */
/* eslint-disable */
/**
 * iRacing OAuth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionsGet200ResponseSessionsInner } from './SessionsGet200ResponseSessionsInner';
import {
    SessionsGet200ResponseSessionsInnerFromJSON,
    SessionsGet200ResponseSessionsInnerFromJSONTyped,
    SessionsGet200ResponseSessionsInnerToJSON,
    SessionsGet200ResponseSessionsInnerToJSONTyped,
} from './SessionsGet200ResponseSessionsInner';

/**
 * 
 * @export
 * @interface SessionsGet200Response
 */
export interface SessionsGet200Response {
    /**
     * 
     * @type {Array<SessionsGet200ResponseSessionsInner>}
     * @memberof SessionsGet200Response
     */
    sessions: Array<SessionsGet200ResponseSessionsInner>;
}

/**
 * Check if a given object implements the SessionsGet200Response interface.
 */
export function instanceOfSessionsGet200Response(value: object): value is SessionsGet200Response {
    if (!('sessions' in value) || value['sessions'] === undefined) return false;
    return true;
}

export function SessionsGet200ResponseFromJSON(json: any): SessionsGet200Response {
    return SessionsGet200ResponseFromJSONTyped(json, false);
}

export function SessionsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'sessions': ((json['sessions'] as Array<any>).map(SessionsGet200ResponseSessionsInnerFromJSON)),
    };
}

export function SessionsGet200ResponseToJSON(json: any): SessionsGet200Response {
    return SessionsGet200ResponseToJSONTyped(json, false);
}

export function SessionsGet200ResponseToJSONTyped(value?: SessionsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessions': ((value['sessions'] as Array<any>).map(SessionsGet200ResponseSessionsInnerToJSON)),
    };
}

