/*
 * iRacing `/data` API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IracingServiceMethodDocsNote {
    String(String),
    ArrayVecString(Vec<String>),
}

impl Default for IracingServiceMethodDocsNote {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
