/*
 * iRacing `/data` API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IracingApiResponse : Response from iRacing `/data` API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IracingApiResponse {
    /// A link to the cached data
    #[serde(rename = "link")]
    pub link: String,
    #[serde(rename = "expires")]
    pub expires: String,
}

impl IracingApiResponse {
    /// Response from iRacing `/data` API.
    pub fn new(link: String, expires: String) -> IracingApiResponse {
        IracingApiResponse {
            link,
            expires,
        }
    }
}

