/*
 * iRacing `/data` API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IracingServiceMethodDocs : An iRacing API Service Method object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IracingServiceMethodDocs {
    #[serde(rename = "link")]
    pub link: String,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters:
        Option<std::collections::HashMap<String, models::IracingServiceMethodParametersDocs>>,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<Box<models::IracingServiceMethodDocsNote>>,
    #[serde(rename = "expirationSeconds", skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<f64>,
}

impl IracingServiceMethodDocs {
    /// An iRacing API Service Method object.
    pub fn new(link: String) -> IracingServiceMethodDocs {
        IracingServiceMethodDocs {
            link,
            parameters: None,
            note: None,
            expiration_seconds: None,
        }
    }
}
