/*
 * iRacing `/data` API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IracingServiceMethodParametersDocs : An iRacing API Service Method Parameters object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IracingServiceMethodParametersDocs {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
}

impl IracingServiceMethodParametersDocs {
    /// An iRacing API Service Method Parameters object.
    pub fn new(r#type: String) -> IracingServiceMethodParametersDocs {
        IracingServiceMethodParametersDocs {
            r#type,
            note: None,
            required: None,
        }
    }
}

