/*
 * iRacing `/data` API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IracingCategory : Racing category.
/// Racing category.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IracingCategory {
    #[serde(rename = "oval")]
    Oval,
    #[serde(rename = "road")]
    Road,
    #[serde(rename = "dirt_road")]
    DirtRoad,
    #[serde(rename = "dirt_oval")]
    DirtOval,
    #[serde(rename = "sports_car")]
    SportsCar,
    #[serde(rename = "formula_car")]
    FormulaCar,

}

impl std::fmt::Display for IracingCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Oval => write!(f, "oval"),
            Self::Road => write!(f, "road"),
            Self::DirtRoad => write!(f, "dirt_road"),
            Self::DirtOval => write!(f, "dirt_oval"),
            Self::SportsCar => write!(f, "sports_car"),
            Self::FormulaCar => write!(f, "formula_car"),
        }
    }
}

impl Default for IracingCategory {
    fn default() -> IracingCategory {
        Self::Oval
    }
}

