name: Publish @iracing-data/oauth-client

on:
  release:
    types:
      - created

jobs:
  publish:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish
        run: |
          cd packages/oauth/client
          pnpm publish --access public

      # Cache build artifacts (for subsequent workflow runs)
      - name: Cache Build Artifacts
        uses: actions/cache@v4
        with:
          path: packages/oauth/client/dist
          key: ${{ runner.os }}-oauth-client-build-${{ github.sha }}
